#!/usr/bin/env node

const commander = require("commander");
const sh = require("shelljs");
const run = (command, errorMessage="Error") => {
  const result = sh.exec(command);
  const exitCode = result.code;
  if (exitCode !== 0) {
    throw `    
     Error: ${errorMessage} (more info probably above)
   command: "${command}"
 exit code: ${exitCode} (should be 0)
` 
  }
  return result;
}

commander.command("demo").action(() => {
  run("npm run build-demo");
  run("npm run deploy-demo");
});

commander
  .command("lib")
  .description('Deploys this library to npm')
  .requiredOption(
    "-v, --version <version>",
    "Designate version: [<newversion> | major | minor | patch]",
    "patch"
  )
  .action((options) => {
    const version = options.version;
    console.log('Deploying version: ' + version)
    run("git diff --exit-code", "You need to commit changes in git first");
    run("npm run test");
    run("npm run build-lib");
    const npmVersion = run("npm version " + version);
    run("npm publish");
    run(`git push origin ${npmVersion}`);
    run('git push');
  });

commander.parse(process.argv);
